
# Após a primeira vez do script rodado, pode remover o # do DROP abaixo, para que exclua e refaça tudo novamente.
#DROP DATABASE SPOTIFEI;

CREATE DATABASE SPOTIFEI;

USE SPOTIFEI;

CREATE TABLE ARTISTA(
	ID_ARTISTA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(45),
    BIO VARCHAR(100)
);

CREATE TABLE MUSICA(
	ID_MUSICA INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(45),
    ALBUM VARCHAR(45),
    DURACAO DECIMAL(5,2),
    TOTAL_OUVINTES INT(),
    ARTISTA_ID INT,
    FOREIGN KEY (ARTISTA_ID) REFERENCES ARTISTA(ID_ARTISTA)
);

CREATE TABLE Planos (
    ID_ASSINATURA INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_ASSINATURA ENUM("BÁSICO", "PREMIUM"),
    VALOR DECIMAL(5,2) NOT NULL,
    TEMPO_MESES INT NOT NULL

CREATE TABLE ASSINATURA_MUSICA(
	ASSINATURA_ID INT,
    MUSICA_ID INT,
    FOREIGN KEY (ASSINATURA_ID) REFERENCES ASSINATURA(ID_ASSINATURA),
    FOREIGN KEY (MUSICA_ID) REFERENCES MUSICA(ID_MUSICA)
);

CREATE TABLE USUARIO(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_USUARIO VARCHAR(45),
    BIO VARCHAR(100),
    ASSINATURA_USUARIO_ID INT,
    FOREIGN KEY (ASSINATURA_USUARIO_ID) REFERENCES ASSINATURA(ID_ASSINATURA)
);


#Inserindo dados dos artistas, para depois verificar qual o ID e colocar no ARTISTA_ID na tabela MUSICA
INSERT INTO ARTISTA(NOME, BIO)
VALUES("AYAKASHI", "AYA");

# Caso não tenha algum valor (assim como o Álbum), pode ser colocado apenas null
# Se precisar ver o ID do artista, só usar a consulta abaixo
# SELECT * FROM ARTISTA
INSERT INTO MUSICA(TITULO, ALBUM, DURACAO, ARTISTA_ID) 
VALUES("Os Mesmos Olhos", null, 3.01, 1);